### ISSUE TITLE
Invoking broccoli builder twice in a single process

### ISSUE THREAD

**Issue by searls** [broccolijs/broccoli#223]
Strap in, because this is probably a very unusual issue that I'm seeking some advice on. If the first section bores you, skip to the second.
#1. initial observations

I'm writing a test suite that invokes `new broccoli.Builder(broccoli.loadBrocfile()).build` multiple times as the suite runs. What I've found is that if `builder.cleanup()` is called after each build (as the broccoli cli does), then subsequent builds will fail with the following:

```
Error: ENOENT, no such file or directory '/some/path/to/project/client_side_template_filter-tmp_cache_dir-unzoh45f.tmp/0'
  at Object.fs.statSync (fs.js:695:18)
  at Object.copyPreserveSync (/Users/justin/code/cabbagejs/cabbage/node_modules/broccoli-filter/node_modules/broccoli-kitchen-sink-helpers/index.js:147:39)
  at copyFromCache (/Users/justin/code/cabbagejs/cabbage/node_modules/broccoli-filter/index.js:108:15)
  at ClientSideTemplateFilter.Filter.processAndCacheFile (/Users/justin/code/cabbagejs/cabbage/node_modules/broccoli-filter/index.js:78:5)
  at /Users/justin/code/cabbagejs/cabbage/node_modules/broccoli-filter/index.js:39:23
  at promise.then.then.results.(anonymous function) (/Users/justin/code/cabbagejs/cabbage/node_modules/broccoli-filter/node_modules/promise-map-series/index.js:8:27)
  at $$$internal$$tryCatch (/Users/justin/code/cabbagejs/cabbage/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:470:16)
  at $$$internal$$invokeCallback (/Users/justin/code/cabbagejs/cabbage/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:482:17)
  at $$$internal$$publish (/Users/justin/code/cabbagejs/cabbage/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:453:11)
  at $$rsvp$asap$$flush (/Users/justin/code/cabbagejs/cabbage/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1531:9)
  at process._tickCallback (node.js:419:13)
```

If I omit the calls to `cleanup`, then I can indeed run multiple builds in a single process, but unfortunately it results in subsequent calls to build being unreliable. For example, my tree will be built differently if a sass file is present, so if I:
1. invoke `build`
2. invoke `cleanup`
3. add a sass file
4. create a new `Builder` and invoke `build` and `cleanup` again
5. the new build will not pick up the new sass file, as if original tree is being re-invoked.

I tried manually `rimraf`'ing the `tmp` directory between builds instead of calling `cleanup`, but that just resulted in a similar stack trace deep inside broccoli calling `mkdirp`, apparently indicating the `broccoli.loadBrocfile()` is holding onto a stale tree in memory.
#2. suggestions

I believe the root cause of this is that `broccoli.loadBrocfile` merely calls `require(brocfile)`, and since a Brocfile must export a tree, and may not return a function that returns a tree, that means it's only going to get loaded once per process.

I would suggest perhaps removing the Brocfile from the [require cache](http://nodejs.org/docs/latest/api/globals.html#globals_require_cache) during `cleanup`. If that's not feasible, then I'd suggest allowing `Brocfile.js` files to export either a tree (as they do now) or a simple function that returns a constructed tree, so that multiple invocations of `loadBrocfile` could detect "a-ha this is a function, let's invoke it again so it can rebuild and return that"

I'm going to spend a little time spiking solutions to these to validate whether I'm crazy, so don't be surprised if I make some sudden drastic edits to this narrative :)

**Comment by joliss** [comment]
Interesting... I'd be interested in the use case that motivates this. Mind sharing?

FYI, in general it seems to me that there's nothing that forces you to go through Broccoli's `loadBrocfile` function. Broccoli doesn't care how you got the root tree you're building, or whether it even came out of a `Brocfile`.

**Comment by searls** [comment]
In my case, the use case is simple a `before` condition in my tests. Each suite of tests starts a fresh `broccoli build` or `broccoli serve` (admittedly through @cabbagejs wrappers, so I could work around calling `loadBrocfile` if I wanted to).

**Comment by rwjblue** [comment]
@searls - I call build many times with different trees in most of the unit tests for my plugin packages.  Should work perfectly here also...

**Comment by stefanpenner** [comment]
This should work fine now. If not, provide a quick example and we can fix.
