### ISSUE TITLE
Error: ENOENT, no such file or directory ../tmp/....tmp while building tree using broccoli Builder

### ISSUE THREAD

**Issue by anandts88** [broccolijs/broccoli#258]
I am trying to run the brocoli build after fingerprinting as like below, but i am getting Error: ENOENT, no such file or directory '/Users/anand/Repos/gitlab/15.1.1/jefferson/tmp/asset_rewrite-tmp_dest_dir-Fw2vCk4H.tmp/.DS_Store'. Can some one please help me?

```
var tree = assetRev('dist', {
  extensions: ['js', 'css'],
  replaceExtensions: ['html'],
  exclude: mobileExclude.concat(desktopExclude),
  generateRailsManifest: true
});

var builder = new broccoli.Builder(tree);
builder.build().then(function(hash) {
    var dir = hash.directory;
    var outputPath = path.join(process.cwd(), 'dist');
    // Delete dist/\* contents
    return rimraf(outputPath).then(function() {
      // move fingerprinted dir into the dist/ dir location
      return copyDereferenceSync(dir, outputPath);
    });
  })
  .finally(function() {
    builder.cleanup();
  })
  .then(function() {
    process.exit(0);
  })
  .catch(function(err) {
    console.error(err.stack);
    console.error('\nBuild failed');
    process.exit(1);
  });
```

**Comment by harmoniemand** [comment]
I am not shure whether this ist the same error, but I got a similar error message.

C:\work\ProjektX.ui>node .\node_modules\broccoli-cli\bin\broccoli build dist
Error: ENOENT: no such file or directory, stat 'C:\work\ProjektX.ui\tmp\source_ma
p_concat-input_base_path-UdptAM75.tmp\0\app\app.js'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at ConcatWithMaps.keyForFile (C:\work\ProjektX.ui\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (C:\work\ProjektX.ui\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\index.js:112:65)
    at C:\work\ProjektX.ui\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (C:\work\ProjektX.ui\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16
)
    at lib$rsvp$$internal$$invokeCallback (C:\work\ProjektX.ui\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\work\ProjektX.ui\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\work\ProjektX.ui\node_modules\broccoli-concat\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)

Build failed

**Comment by iDev0urer** [comment]
Similar problem here:

```shell
Running "broccoli:dev:build" (broccoli) task
out\static_resources\CC_Assets_CW\App out\classes\ out\pages\
>> Error: ENOENT: no such file or directory, mkdir 'C:\Users\FA-0042\Documents\Projects\salesforce\JohnsonControls\buildresources\tmp\funnel-output_path-NWeMsysm.tmp\out\pages'
```

**Comment by micky2be** [comment]
Same problem here. Issue has been opened 2 years ago

**Comment by stefanpenner** [comment]
I don't believe this a broccoli bug, rather one in one of the plugins you are using. Surprisingly broccoli itself does no filesystem reading stuff itself.

I am closing this issue, but if someone runs into it with modern plugins. Please share clear/concise reproduction steps, and I will gladly reopen + debug and hopefully help solve
