### ISSUE TITLE
No inputTree/inputTrees set on tree: CoreObject

### ISSUE THREAD

**Issue by mitchlloyd** [broccolijs/broccoli#274]
Started getting this error today on a deployment around 3:30pm PDT. When I removed my dependencies locally and reinstalled them I see the same error:

```
A new version of ember-cli is available (1.13.8). To install it, type ember update.
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
StylesReloader is disabled
Serving on http://localhost:4200/
No inputTree/inputTrees set on tree: CoreObject
Error: No inputTree/inputTrees set on tree: CoreObject
    at NewStyleTreeWrapper.read (/Users/mitchlloyd/projects/web-developer/frontend/node_modules/ember-cli/node_modules/broccoli/lib/api_compat.js:27:11)
    at /Users/mitchlloyd/projects/web-developer/frontend/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:79:23
    at lib$rsvp$$internal$$tryCatch (/Users/mitchlloyd/projects/web-developer/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/mitchlloyd/projects/web-developer/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at /Users/mitchlloyd/projects/web-developer/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/Users/mitchlloyd/projects/web-developer/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at process._tickCallback (node.js:355:11)
```

Assuming this is some dependency update but having trouble tracking down the issue. Doesn't seem like CoreObject has been updated in a while. Will continue to debug but wanted to raise an issue in case others see the same thing.

**Comment by dortort** [comment]
Same here. Broken builds since this morning.
```
Build failed.
No inputTree/inputTrees set on tree: CoreObject
Error: No inputTree/inputTrees set on tree: CoreObject
    at NewStyleTreeWrapper.read (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CTI-UI-JOB1/node_modules/ember-cli/node_modules/broccoli/lib/api_compat.js:27:11)
    at /home/bamboo/bamboo-agent-home/xml-data/build-dir/CTI-UI-JOB1/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:97:23
    at lib$rsvp$$internal$$tryCatch (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CTI-UI-JOB1/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CTI-UI-JOB1/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at /home/bamboo/bamboo-agent-home/xml-data/build-dir/CTI-UI-JOB1/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1001:13
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/home/bamboo/bamboo-agent-home/xml-data/build-dir/CTI-UI-JOB1/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by dortort** [comment]
Downgrading ember-browserify to 1.0.3 works for me. (https://github.com/ef4/ember-browserify/issues/44)

**Comment by stefanpenner** [comment]
This isn't a bug rather. Ember-browserify currently fails to call super constructor.

**Comment by rwjblue** [comment]
Hehe, well it is a bug. Just not here :smiling_imp:...

**Comment by stefanpenner** [comment]
https://github.com/ef4/ember-browserify/issues/44#issuecomment-133433371
