### ISSUE TITLE
errors in build are not listed in console output

### ISSUE THREAD

**Issue by BryanCrotaz** [broccolijs/broccoli#299]
E.g. merge with conflicting archive filenames without setting the `overwrite`option.

```
C:\projects\sc-pp\test>broccoli-clext build --no-watchman
Building.BroccoliArchiver.prototype.build
Building...saving keys to C:\projects\sc-pp\test\tmp\broccoli_archiver-cache_path-py60Jvic.tmp/lastKeys.json
BroccoliArchiver.prototype.build
saving keys to C:\projects\sc-pp\test\tmp\broccoli_archiver-cache_path-QOZNIY55.tmp/lastKeys.json


Build failed.
```

Note that no information about why the build failed makes it to the console. This makes debugging **really** hard.

**Comment by stefanpenner** [comment]
```js
class Foo extends require('broccoli-plugin'){
  build() {
    throw 'OMG';
  }
}

module.exports =  new Foo(['foo']);
```

running:

```sh
broccoli serve
```

Produces:

```
Error: OMG
    at wrapPrimitiveErrors (/Users/spenner/tmp/broc-demo/node_modules/broccoli/lib/builder.js:546:12)
    at new BuildError (/Users/spenner/tmp/broc-demo/node_modules/broccoli/lib/builder.js:345:19)
    at /Users/spenner/tmp/broc-demo/node_modules/broccoli/lib/builder.js:107:19
    at tryCatch (/Users/spenner/tmp/broc-demo/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/spenner/tmp/broc-demo/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/spenner/tmp/broc-demo/node_modules/rsvp/dist/rsvp.js:508:7)
    at publishRejection (/Users/spenner/tmp/broc-demo/node_modules/rsvp/dist/rsvp.js:443:3)
    at flush (/Users/spenner/tmp/broc-demo/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Build failed
```


Clearly this error logging could be improved. Example of much better output is: https://github.com/ember-cli/console-ui/pull/14#issuecomment-346495211
