### ISSUE TITLE
1.1.3 broken due to incompatible broccoli-slow-trees

### ISSUE THREAD

**Issue by chrmod** [broccolijs/broccoli#322]
Have reported that on broccoli-slow-trees some time ago:
https://github.com/rwjblue/broccoli-slow-trees/issues/9

Serving any project with 1.1.3 prints following errors:
```
Serving on http://localhost:4200

Error when printing slow nodes: TypeError: tree.visitPostOrder is not a function
    at calculateSummary (/home/chrmod/tmp/bro/node_modules/broccoli-slow-trees/calculate-summary.js:27:8)
    at printSlowNodes (/home/chrmod/tmp/bro/node_modules/broccoli-slow-trees/index.js:13:19)
    at /home/chrmod/tmp/bro/node_modules/broccoli/lib/server.js:32:5
    at Watcher.trigger (/home/chrmod/tmp/bro/node_modules/rsvp/dist/rsvp.js:199:9)
    at /home/chrmod/tmp/bro/node_modules/broccoli/lib/watcher.js:88:10
    at tryCatch (/home/chrmod/tmp/bro/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/chrmod/tmp/bro/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/chrmod/tmp/bro/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/home/chrmod/tmp/bro/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
TypeError: tree.visitPostOrder is not a function
    at calculateSummary (/home/chrmod/tmp/bro/node_modules/broccoli-slow-trees/calculate-summary.js:27:8)
    at printSlowNodes (/home/chrmod/tmp/bro/node_modules/broccoli-slow-trees/index.js:13:19)
    at /home/chrmod/tmp/bro/node_modules/broccoli/lib/server.js:32:5
    at Watcher.trigger (/home/chrmod/tmp/bro/node_modules/rsvp/dist/rsvp.js:199:9)
    at /home/chrmod/tmp/bro/node_modules/broccoli/lib/watcher.js:88:10
    at tryCatch (/home/chrmod/tmp/bro/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/chrmod/tmp/bro/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/chrmod/tmp/bro/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/home/chrmod/tmp/bro/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
Built - 0 ms @ Sat Jul 29 2017 21:44:30 GMT+0200 (CEST)
```

here is a PR that fixes the issue: https://github.com/broccolijs/broccoli/pull/321

**Comment by chrmod** [comment]
fixed by https://github.com/broccolijs/broccoli/pull/321 - released in 1.1.4
